---
title: 'Identifying Risk Factors and Preferred Hospitals for Hip/Knee Replacements:
  An Analysis of 2024 Hospital Readmission Reduction Program Data'
author: "Adeline Casali and Scott Eugley"
date: "2024-07-09"
output: html_document
---

# Background  
Since 2012, the Centers for Medicare and Medicaid Services have implemented the Hospital Readmission Reduction Program (HRRP). This program tracks hospital readmission rates and incentivizes hospitals to reduce unnecessary readmissions through financial penalties. Using the 2024 readmission data from the HRRP, this analysis aims to identify the preferred and non-preferred hospitals for hip and knee replacements for a health insurance company. Furthermore, it will examine the risk factors associated with higher readmission rates for these procedures.  

# Question  
What risk factors are associated with hospital readmission rates for hip/knee replacements?  

# Hypothesis and Prediction  
Hospitals with better Hospital Consumer Assessment of Healthcare Providers and Systems (HCAHPS) scores will have lower readmission rates for hip/knee replacements because higher patient satisfaction often correlates with better overall care quality and patient outcomes, including reduced complications and better post-discharge support.  
